apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v9b6506he-java-quarkus
  janus-idp.io/tekton: v9b6506he-java-quarkus
  backstage.io/kubernetes-id: v9b6506he-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v9b6506he-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
